version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.app
    restart: always
    container_name: products-app
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    environment:
    - DB_HOST=mysql
    - DB_USER=user
    - DB_PASSWORD=password
    - DB_NAME=ProductsAppDb
    - APP_USER=admin
    - APP_USER_PASSWORD=admin

  mysql:
    image: mysql:latest
    restart: always
    container_name: products-mysql-container
    environment:
      MYSQL_DATABASE: "ProductsAppDb"
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "password"
      MYSQL_ROOT_PASSWORD: "password"
    ports:
      - "3306:3306"
    expose: 
      - "3306"
    volumes:
      - mysql_data:/var/lib/mysql  

volumes:
  mysql_data: