version: '3.8'

services:
  mysql:
    image: mysql:latest
    restart: always
    container_name: products-mysql-container
    environment:
      MYSQL_DATABASE: "ProductsAppDb"
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "password"
      MYSQL_ROOT_PASSWORD: "password"
    ports:
      - "3306:3306"
    expose: 
      - "3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: